services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: frontend
    env_file:
      - frontend/.env
    volumes:
      - frontend:/app/frontend/dist

  mongo:
    image: mongo:4.4.29
    container_name: mongo_4_4_29
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mdb:/data/db
    ports:
      - 27017:27017
    networks:
      - internal

  backend:
    image: backend
    restart: always
    container_name: backend
    build:
      context: backend
    env_file:
      - backend/.env
    ports:
      - 3000:3000
    volumes:
      - public:/usr/src/app/dist/public
    networks:
      - internal
    depends_on:
      - mongo

  server:
    image: server
    container_name: nginx
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - frontend:/var/app
      - public:/var/public
    depends_on:
      - frontend
      - backend
    networks:
      - internal
      - internet

volumes:
  frontend:
    name: frontend
  public:
    name: public
  mdb:
    name: mdb

networks:
  internet:
    name: internet
    driver: bridge
  internal:
    name: internal
    driver: bridge
    internal: true
